"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#b4befe)\
$os\
[ ](bg:#45475a fg:#b4befe)\
$directory\
[ ](fg:#45475a bg:#313244)\
$git_branch\
$git_status\
[ ](fg:#313244 bg:#1e1e2e)\
$nodejs\
$bun\
$rust\
$golang\
$php\
[ ](fg:#1e1e2e bg:#11111b)\
$time\
[ ](fg:#11111b)\
\n$character"""

[character]
success_symbol = "[>>>](bold #b4befe)"
error_symbol = "[>>>](bold #f38ba8)"

[directory]
style = "fg:#cdd6f4 bg:#45475a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#313244"
format = '[[ $symbol $branch ](fg:#b4befe bg:#313244)]($style)'

[git_status]
style = "bg:#313244"
format = '[[($all_status$ahead_behind )](fg:#b4befe bg:#313244)]($style)'

[nodejs]
symbol = ""
style = "bg:#1e1e2e"
format = '[[ $symbol ($version) ](fg:#b4befe bg:#1e1e2e)]($style)'

[bun]
symbol = ""
style = "bg:#1e1e2e"
format = '[[ $symbol ($version) ](fg:#b4befe bg:#1e1e2e)]($style)'

[rust]
symbol = ""
style = "bg:#1e1e2e"
format = '[[ $symbol ($version) ](fg:#b4befe bg:#1e1e2e)]($style)'

[golang]
symbol = ""
style = "bg:#1e1e2e"
format = '[[ $symbol ($version) ](fg:#b4befe bg:#1e1e2e)]($style)'

[php]
symbol = ""
style = "bg:#1e1e2e"
format = '[[ $symbol ($version) ](fg:#b4befe bg:#1e1e2e)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#11111b"
format = '[[  $time ](fg:#b4befe bg:#11111b)]($style)'

[os]
style = "bg:#b4befe fg:#11111b"
format = "[ $symbol ]($style)"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
NixOS = "󱄅"
